# Server
server.port=8087
  
  # PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cl
spring.datasource.username=postgres
spring.datasource.password=24142
spring.datasource.driver-class-name=org.postgresql.Driver
  
  # JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
  
  # Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
  
  # Session
server.servlet.session.timeout=30m
spring.mvc.hiddenmethod.filter.enabled=true
  
  # App name
spring.application.name=Real Estate Portal